'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FFmpegFreeUI.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property AppIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 完成() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("完成", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enter  --&gt;  开始
        '''Space  --&gt;  暂停
        '''Ctrl + A  --&gt;  全选
        '''Alt + A  --&gt;  反选
        '''Delete  --&gt;  移除
        '''Esc  --&gt;  重置
        '''End  --&gt;  停止
        '''F3  --&gt;  上移
        '''F4  --&gt;  下移 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 编码队列快捷键() As String
            Get
                Return ResourceManager.GetString("编码队列快捷键", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {
        '''  &quot;Button.StartMission&quot;: &quot;Start&quot;,
        '''  &quot;Button.PauseMission&quot;: &quot;Pause&quot;,
        '''  &quot;Button.ResumeMission&quot;: &quot;Resume&quot;,
        '''  &quot;Button.StopMission&quot;: &quot;Stop&quot;,
        '''  &quot;Button.RemoveMission&quot;: &quot;Remove&quot;,
        '''  &quot;Button.ResetMission&quot;: &quot;Reset&quot;,
        '''  &quot;Button.LocateMission&quot;: &quot;Locate&quot;,
        '''  &quot;Button.MissionMenu&quot;: &quot;Mission Menu&quot;,
        '''  &quot;Label.Status&quot;: &quot;Status&quot;,
        '''  &quot;Label.Progress&quot;: &quot;Progress&quot;,
        '''  &quot;Label.Speed&quot;: &quot;Speed&quot;,
        '''  &quot;Label.OutputSize&quot;: &quot;Size &amp;&amp; Remaining&quot;,
        '''  &quot;Label.Quality&quot;: &quot;q&quot;,
        '''  &quot;Label.Bitrate&quot;: &quot;Bitrate&quot;,
        '''  &quot;Label.TimeRemaining&quot;: &quot;Time [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 语言_en() As String
            Get
                Return ResourceManager.GetString("语言_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {
        '''  &quot;Button.StartMission&quot;: &quot;开始&quot;,
        '''  &quot;Button.PauseMission&quot;: &quot;暂停&quot;,
        '''  &quot;Button.ResumeMission&quot;: &quot;恢复&quot;,
        '''  &quot;Button.StopMission&quot;: &quot;停止&quot;,
        '''  &quot;Button.RemoveMission&quot;: &quot;移除&quot;,
        '''  &quot;Button.ResetMission&quot;: &quot;重置&quot;,
        '''  &quot;Button.LocateMission&quot;: &quot;定位&quot;,
        '''  &quot;Button.MissionMenu&quot;: &quot;任务管理菜单&quot;,
        '''  &quot;Label.Status&quot;: &quot;状态&quot;,
        '''  &quot;Label.Progress&quot;: &quot;进度&quot;,
        '''  &quot;Label.Speed&quot;: &quot;效率&quot;,
        '''  &quot;Label.OutputSize&quot;: &quot;输出大小 &amp;&amp; 预估&quot;,
        '''  &quot;Label.Quality&quot;: &quot;质量&quot;,
        '''  &quot;Label.Bitrate&quot;: &quot;比特率&quot;,
        '''  &quot;Label.TimeRemaining&quot;: &quot;预计剩余 &amp;&amp; 已用&quot;,
        '''  &quot;LinkLabel.Send&quot;: &quot;发送&quot;,
        '''  &quot;LinkLabel.Sw [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 语言_zh() As String
            Get
                Return ResourceManager.GetString("语言_zh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 错误() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("错误", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
