'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FFmpegFreeUI.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property AppIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AppIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property 完成() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("完成", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 易相逢|#FBE4FF
        '''夜枫|#CCA4A3
        '''爱发电用户_Ck8g
        '''David King
        '''Daydreamer|#037DEC
        '''爱发电用户_217cb
        '''BAILING (学生)|#905BD9
        '''zhengjun638504@163.com 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property 支持者名单() As String
            Get
                Return ResourceManager.GetString("支持者名单", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 格里芬指挥官|#39C5BB
        '''陆耀YSNX462 (FFBOX最严厉的父亲)|#66FF66
        '''Celery (酒吧点蛋炒饭的)|#21AEFF
        '''哈哈6662333 (坏点子大师/&quot;网&quot;管)|#FF9633
        '''哈基曼波|#FF96DE
        '''ZOGMOS (终末诗) (首席教程制作大师) (开发者特别授予)|#72565F|终末诗
        '''Uyanide (I use arch btw) (首席二次元)|#89B4FA
        '''Simlalsy (压片的)|#E3E0F9 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property 支持者名单_赠送() As String
            Get
                Return ResourceManager.GetString("支持者名单_赠送", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enter  --&gt;  开始
        '''Space  --&gt;  暂停
        '''Ctrl + A  --&gt;  全选
        '''Alt + A  --&gt;  反选
        '''Delete  --&gt;  移除
        '''Esc  --&gt;  重置
        '''End  --&gt;  停止
        '''F3  --&gt;  上移
        '''F4  --&gt;  下移 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property 编码队列快捷键() As String
            Get
                Return ResourceManager.GetString("编码队列快捷键", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {
        '''  &quot;Label.SubTitle&quot;: &quot;Simply add FFmpeg to environment variables or place it in the 3FUI directory to use.&quot;,
        '''  &quot;Label.LinkAndDocument&quot;: &quot;Link And Document&quot;,
        '''  &quot;Label.DonotTrustAI&quot;: &quot;Do Not Trust AI !&quot;,
        '''  &quot;Label.3FUIGithubRepository&quot;: &quot;3FUI Github Repository&quot;,
        '''  &quot;Label.FFmpegOfficialDoc&quot;: &quot;FFmpeg Official Doc (ffmpeg.org)&quot;,
        '''  &quot;Label.DownloadFFmpegGyandev&quot;: &quot;Download FFmpeg (gyan.dev)&quot;,
        '''  &quot;Label.DownloadFFmpegBtbN&quot;: &quot;Download FFmpeg (BtbN)&quot;,
        '''  &quot;Label.afdian&quot;: &quot;Sponsor (afdian)&quot;,
        '''  &quot;Label.bilibili&quot;:  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property 语言_en() As String
            Get
                Return ResourceManager.GetString("语言_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 {
        '''  &quot;Label.SubTitle&quot;: &quot;将 FFmpeg 加入环境变量或放置于 3FUI 程序目录下即可调用&quot;,
        '''  &quot;Label.LinkAndDocument&quot;: &quot;链接和文档&quot;,
        '''  &quot;Label.DonotTrustAI&quot;: &quot;不要相信 AI&quot;,
        '''  &quot;Label.3FUIGithubRepository&quot;: &quot;3FUI Github 仓库&quot;,
        '''  &quot;Label.FFmpegOfficialDoc&quot;: &quot;FFmpeg 官方文档（ffmpeg.org）&quot;,
        '''  &quot;Label.DownloadFFmpegGyandev&quot;: &quot;下载 FFmpeg（gyan.dev）&quot;,
        '''  &quot;Label.DownloadFFmpegBtbN&quot;: &quot;下载 FFmpeg（BtbN）&quot;,
        '''  &quot;Label.afdian&quot;: &quot;赞助一下（afdian）&quot;,
        '''  &quot;Label.bilibili&quot;: &quot;作者主页（哔哩哔哩）&quot;,
        '''  &quot;Label.OfficialWebsite1&quot;: &quot;官网 ffmpegfreeui.top&quot;,
        '''  &quot;Label.OfficialWebsite2&quot;: &quot;官网 3fui.top [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property 语言_zh() As String
            Get
                Return ResourceManager.GetString("语言_zh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        '''</summary>
        Public Shared ReadOnly Property 错误() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("错误", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
